version: "3"
services:
  mongo:
    container_name: mongo-kapivara-container
    image: mongo:3
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - "${PORT}:${PORT}"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/api-kapivara/src
    restart: unless-stopped
    command: bash -c "npm install && npm run dev"
    environment:
      - MONGO_URL=mongodb://mongo:${PORT}/kapivara
    volumes:
      - .:/usr/api-kapivara/src/
      - ./package.json:/usr/src/api-kapivara/package.json
    ports:
      - "3000:3000"
    links:
      - mongo